@AzureStorageBlob_HostAddress = https://localhost:7036

GET {{AzureStorageBlob_HostAddress}}/weatherforecast

###

####### Container operations

@containerName=mycontainer

POST {{AzureStorageBlob_HostAddress}}/api/v1/container/create-container-body
Content-Type: application/json

"mycontainer3"

###

POST {{AzureStorageBlob_HostAddress}}/api/v1/container/create-container-param?containerName={{containerName}}

###

DELETE {{AzureStorageBlob_HostAddress}}/api/v1/container/delete-container?containerName={{containerName}}

###

POST {{AzureStorageBlob_HostAddress}}/api/v1/container/create-container/{{containerName}}

###

GET {{AzureStorageBlob_HostAddress}}/api/v1/container/container-list

###

### Blob operations

POST {{AzureStorageBlob_HostAddress}}/blob/upload-blob/{{containerName}}
Content-Type: multipart/form-data

-F "file=@C:/Users/Shree/Downloads/BlobUploadTest.jpg"

### postman curl
//curl --location 'https://localhost:7036/blob/upload-blob/mycontainer' \
//--form 'file=@"file_path"'

###

@blobName=ID Card Photo11.jpg
GET {{AzureStorageBlob_HostAddress}}/blob/blob-list/{{containerName}}

###

GET {{AzureStorageBlob_HostAddress}}/blob/get-blob/{{containerName}}/{{blobName}}

###

GET {{AzureStorageBlob_HostAddress}}/blob/get-blob-metadata/{{containerName}}?blobName={{blobName}}

###

DELETE {{AzureStorageBlob_HostAddress}}/api/blob/blob-delete/{{containerName}}/{{blobName}}

###

DELETE {{AzureStorageBlob_HostAddress}}/blob/delete-multiple-blobs/{{containerName}}
Content-Type: application/json
[
  "133821007122555688_2.jpg",
  "BlobUploadTest.jpg"
]
###

GET {{AzureStorageBlob_HostAddress}}/blob/download/{{containerName}}/{{blobName}}

###

POST {{AzureStorageBlob_HostAddress}}/blob/upload-blob-tier/{{containerName}}

# curl --location 'https://localhost:7036/blob/upload-blob-tier/mycontainer' \
# --form 'File=@"choose file' \
# --form 'AccessTier="cool"'

###

POST {{AzureStorageBlob_HostAddress}}/blob/upload-blob-metadata
Content-Type: application/json

{
  //BlobUploadMetadataRequest
}

# curl --location 'https://localhost:7036/blob/upload-blob-metadata' \
# --form 'File=@"/C:/Users/Shree/OneDrive/Pictures/133821007122555688_2.jpg"' \
# --form 'ContainerName="mycontainer"' \
# --form 'MetaData[author]="Netaji"'


###
